[workspace]
resolver = "2"

members = [
  "hook-common",
  "hook-producer",
  "hook-consumer",
]

[workspace.dependencies]
chrono = { version = "0.4" }
serde = { version = "1.0" }
serde_derive = { version = "1.0" }
thiserror = { version = "1.0" }
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-native-tls", "postgres", "uuid", "json", "chrono" ] }
tokio = { version = "1.34.0", features = ["full"] }
eyre = "0.6.9"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
envconfig = "0.10.0"
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.1"
