[workspace]
resolver = "2"

members = [
  "hook-common",
  "hook-producer",
  "hook-consumer",
]

[workspace.dependencies]
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-native-tls", "postgres", "uuid", "json" ] }
